docker:
  image: "gradle:jdk17-jammy"
env:
  JAVA_HOME: "/opt/java/openjdk"
  GRADLE_USER_HOME: "$HOME/gradle"
merge:
  fast-forward: yes
  script: |
    mkdir -p $GRADLE_USER_HOME
    ./gradlew --no-daemon check 
