[versions]
springBoot = "3.2.5"
springDeps = "1.1.5"

[libraries]
log4jdbc = { module = "org.bgee.log4jdbc-log4j2:log4jdbc-log4j2-jdbc4.1", version = "1.16" }
lombok = { module = "org.projectlombok:lombok", version = "1.18.32" }
spring-boot-deps = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot" }

[plugins]
axion-release = { id = "pl.allegro.tech.build.axion-release", version = "1.17.1" }
kt3k-coveralls = { id = "com.github.kt3k.coveralls",  version = "2.12.2" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }
spring-deps-management = { id = "io.spring.dependency-management", version.ref = "springDeps" }