name: Project release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        required: true
        description: "New release version. Has to be SemVer compliant, ex. '1.2.3'"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'

      - name: Release new version
        id: release
        run: |
          ./gradlew release \
            -Prelease.version=${{ github.event.inputs.releaseVersion }} \
            -Prelease.customUsername=${{ github.actor }} \
            -Prelease.customPassword=${{ github.token }}

      - name: Publish to Sonatype
        id: publish_release
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USER }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASS }}
          GPG_KEY: ${{ secrets.GPG_KEY }}
          GPG_PASS: ${{ secrets.GPG_PASS }}
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository

      - name: GitHub Release
        id: github_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.event.inputs.releaseVersion }}
          release_name: ${{ github.event.inputs.releaseVersion }}
          body: |
            ### ⭐ New Features
             - none
            ### 🐞 Bug fixes
             - none
          draft: true
          prerelease: false
