name: Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        required: true
        description: "New release version. Has to be SemVer compliant, ex. '1.2.3'"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --prune --unshallow --tags

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'

      - name: Release new version
        id: release
        run: |
          ./gradlew --info release \
            -Prelease.version=${{ github.event.inputs.releaseVersion }} \
            -Prelease.customUsername=${{ github.actor }} \
            -Prelease.customPassword=${{ github.token }}

      - name: Publish to Sonatype
        id: publish_release
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USER }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASS }}
          GPG_KEY: ${{ secrets.GPG_KEY }}
          GPG_PASS: ${{ secrets.GPG_PASS }}
        run: ./gradlew --info publishToSonatype closeAndReleaseSonatypeStagingRepository

      - name: GitHub Release
        id: github_release
        uses: ncipollo/release-action@v1.13.0
        with:
          name: ${{ github.event.inputs.releaseVersion }}
          tag: ${{ github.event.inputs.releaseVersion }}
          commit: master
          body: |
            ### ⭐ New Features
             - none
            ### 🐞 Bug fixes
             - none
          draft: true
          removeArtifacts: true
